name: german_to_eng_translator
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit
      - torch
      - requests
      - transformers
      - gtts
      - soundfile
      - ollama
